### ISSUE TITLE
create json api to create mobile apps 

### ISSUE THREAD

**Issue by quickstreamingmedia** [jprjr/multistreamer#12] opened 2017-04-20 07:03 UTC
please create api for multistreamer to create mobile apps

**Comment by jprjr** [comment] 2017-04-20 12:15
That's actually something I had been thinking about - glad to hear there's interest! Not sure when I'll get it done, but it's on my list

On April 20, 2017 2:03:20 AM CDT, Venkatesh Gajula <notifications@github.com> wrote:
>please create api for multistreamer to create mobile apps
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/multistreamer/issues/12

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by quickstreamingmedia** [comment] 2017-04-21 15:40
i will contribute to it i hope it will be easy

**Comment by jprjr** [comment] 2017-04-22 18:00
Alright, I think I've banged out a JSON API to cover all the use cases - take a look at the wiki:

https://github.com/jprjr/multistreamer/wiki/JSON

I also documented the websocket API used for sending/receiving chat messages

https://github.com/jprjr/multistreamer/wiki/WebSocket

**Comment by quickstreamingmedia** [comment] 2017-07-07 19:03
./bin/multistreamer -e production run
/usr/bin/lua: error loading module 'posix.ctype' from file '/root/multistreamer/lua_modules/lib/lua/5.1/posix.so':
        /root/multistreamer/lua_modules/lib/lua/5.1/posix.so: undefined symbol: luaL_fileresult
stack traceback:
        [C]: ?
        [C]: in function 'require'
        ...ltistreamer/lua_modules/share/lua/5.1/posix/init.lua:29: in main chunk
        [C]: in function 'require'
        /root/multistreamer/bin/multistreamer.lua:12: in main chunk
        [C]: ?
how to fix this issue? @jprjr

**Comment by jprjr** [comment] 2017-07-07 23:32
That usually happens if you start multistreamer with a different version of lua than you compiled the lua modules with. Multistreamer tries to use luajit, if it's on the path, then lua.

You can specify which lua to use with the -l switch, so try something like:

```
./bin/multistreamer -e production -l /path/to/luajit run
```

**Comment by quickstreamingmedia** [comment] 2017-07-09 12:12
./bin/multistreamer -e production -l /opt/openresty-rtmp/luajit/bin/luajit run
/opt/openresty-rtmp/luajit/bin/luajit: ...multistreamer/lua_modules/share/lua/5.1/lapis/config.lua:133: error loading module 'config' from file './config.lua':
        ./config.lua:96: unfinished string near '','
stack traceback:
        [C]: in function 'error'
        ...multistreamer/lua_modules/share/lua/5.1/lapis/config.lua:133: in function 'get'
        ./multistreamer/config.lua:1: in main chunk
        [C]: in function 'require'
        /root/multistreamer/bin/multistreamer.lua:51: in main chunk
        [C]: at 0x004047d0
@jprjr

**Comment by jprjr** [comment] 2017-07-09 15:39
I would check between lines 94 and 96 of your config.lua file and make sure you don't have any runaway quotes

**Comment by quickstreamingmedia** [comment] 2017-07-10 06:05
![image](https://user-images.githubusercontent.com/6527923/28004679-7309dc10-6570-11e7-8e01-5d434d13aade.png)

docker gives me following error

**Comment by quickstreamingmedia** [comment] 2017-07-10 07:35
main version is working fine but i cannot connect to streamign server 

![image](https://user-images.githubusercontent.com/6527923/28007267-ee3e29fc-657c-11e7-8bf8-5f8fe108078e.png)

![image](https://user-images.githubusercontent.com/6527923/28007274-fda5ef7e-657c-11e7-8e87-2e433fd34c43.png)

**Comment by quickstreamingmedia** [comment] 2017-07-10 08:13
![image](https://user-images.githubusercontent.com/6527923/28008565-3ea2f68e-6582-11e7-9216-7a2a5b21ff3a.png)

one more issue

**Comment by quickstreamingmedia** [comment] 2017-07-10 08:18
![image](https://user-images.githubusercontent.com/6527923/28008778-148dae9c-6583-11e7-946e-973ffc002160.png)

**Comment by jprjr** [comment] 2017-07-10 11:14
Make sure you're on the latest 9.0.1, I some of these errors you're seeing are from older versions

On July 10, 2017 3:18:56 AM CDT, Venkatesh Gajula <notifications@github.com> wrote:
>![image](https://user-images.githubusercontent.com/6527923/28008778-148dae9c-6583-11e7-946e-973ffc002160.png)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/multistreamer/issues/12#issuecomment-314037542

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jprjr** [comment] 2017-07-10 11:41
For the network being unreachable, it's usually because dns have an ipv6 response but whatever multistreamer is running on doesn't support ipv6.

Try setting the DNS resolver to `8.8.8.8 ipv6=off`

On July 10, 2017 3:18:56 AM CDT, Venkatesh Gajula <notifications@github.com> wrote:
>![image](https://user-images.githubusercontent.com/6527923/28008778-148dae9c-6583-11e7-946e-973ffc002160.png)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/multistreamer/issues/12#issuecomment-314037542

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by quickstreamingmedia** [comment] 2017-07-10 17:39
![image](https://user-images.githubusercontent.com/6527923/28031397-5a095702-65d1-11e7-9d41-a0ad7170d700.png)

i have checked with resolving issue fine facebook still issue i use latest version it self

**Comment by quickstreamingmedia** [comment] 2017-07-10 17:44
![image](https://user-images.githubusercontent.com/6527923/28031600-04965e7c-65d2-11e7-9cbe-c92984c3fc5f.png)
this is the final image

**Comment by jprjr** [comment] 2017-07-10 18:38
For facebook: double-check you have `9.0.1` pulled down. There's no way for `len` to be undefined in 9.0.1

That `Unrecoverable error` message usually means multistreamer couldn't connect to redis or sockexec. Check the logs and make sure `redis-server` is running.

**Comment by quickstreamingmedia** [comment] 2017-07-10 21:10
i have pulled master branch and as of logs i see its edited on jun4

**Comment by jprjr** [comment] 2017-07-10 22:07
I would suggest saving your config.lua, wipe out and replace multistreamer. `9.0.1` was released on July 6

**Comment by quickstreamingmedia** [comment] 2017-07-11 23:15
![image](https://user-images.githubusercontent.com/6527923/28094854-6b36f216-66c9-11e7-885d-c59a513d23c8.png)

after adding youtube

**Comment by jprjr** [comment] 2017-07-11 23:15
On the dashboard, you have to choose a category for your video

On July 11, 2017 6:15:04 PM CDT, Venkatesh Gajula <notifications@github.com> wrote:
>![image](https://user-images.githubusercontent.com/6527923/28094854-6b36f216-66c9-11e7-885d-c59a513d23c8.png)
>
>after adding youtube
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/multistreamer/issues/12#issuecomment-314598027

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by quickstreamingmedia** [comment] 2017-07-12 02:22
no categories showing in dash board i check drop down already

**Comment by jprjr** [comment] 2017-07-12 02:43
What is your country code set to, in your config.lua?

**Comment by quickstreamingmedia** [comment] 2017-07-12 04:00
country is KH and some pcs getting error like this 
![image](https://user-images.githubusercontent.com/6527923/28101228-522ae688-66f1-11e7-9adf-d95f7930f3b9.png)

**Comment by jprjr** [comment] 2017-07-12 04:38
re: youtube - it looks like kh doesn't return any video categories - you can test country codes here: https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.videoCategories.list?part=snippet&regionCode=kh&_h=2& - I'd just pick another country code nearby that gives categories

re: facebook - I just committed a fix, pull down from master and give that a try

**Comment by quickstreamingmedia** [comment] 2017-07-12 06:21
youtube does not work i have enabled what you have mentioned in document

**Comment by jprjr** [comment] 2017-07-12 12:37
For YouTube: go to https://www.youtube.com/live_dashboard and make sure your YouTube account has livestreaming enabled.

**Comment by quickstreamingmedia** [comment] 2017-07-16 22:53
youtube is fine able to work for all users who have live streaming enabled. but for facebook it cannot stream to other accounts except mine may i know solution for it ?

**Comment by jprjr** [comment] 2017-07-17 00:42
Have you submitted the app to Facebook for review? If you haven't done that yet (it's a process, you have to write up a privacy policy, create an icon, etc), only admins of the Facebook app can use the live video features. Details here: https://developers.facebook.com/docs/facebook-login/review/requirements

I only have 3 other people using my instance of Multistreamer, so I just added them all as admins to the app.

**Comment by jprjr** [comment] 2017-07-17 20:48
You might be able to just add people as testers of the app and leave it in development mode, instead of adding them as administrators.

The docs only list "admins", but sometimes the docs are out-of-sync from reality - https://developers.facebook.com/docs/videos/live-video/getting-started#permissions

**Comment by jprjr** [comment] 2017-07-19 14:17
I just confirmed, it looks like you can add users as "testers" to the app instead of admins

**Comment by quickstreamingmedia** [comment] 2017-07-30 06:24
i got approval from facebook for live video api. still it says app does not have permissions to stream i need to check what the issue. is there any additional details required to make in the app.

**Comment by jprjr** [comment] 2017-07-30 22:45
Not that I can think of, at this point it should all be working

**Comment by quickstreamingmedia** [comment] 2017-07-31 03:57
thank you so much @jprjr  for quick support everything is working fine now.

**Closed** 2017-11-21 11:22 UTC
